import hashTablesJson from '../data/hash-tables.json';
import civ6TypesJson from '../data/civ6-types.json';

export interface TerrainEntry {
    name: string;
    form: string | null;
}

export interface HashTables {
    terrains: Record<string, TerrainEntry>;
    features: Record<string, string>;
    resources: Record<string, string>;
    improvements: Record<string, string>;
    continents: Record<string, string>;
    roads: Record<string, string>;
    instanceTypes?: Record<string, string>;
}

const TABLES: HashTables = hashTablesJson as HashTables;

export function hashHex(hash: number): string {
    return (hash >>> 0).toString(16).padStart(8, '0');
}

/** Civ6Save Data Sheet ints are byte-reversed in some plot fields (notably improvements). */
export function bswap32(hash: number): number {
    const n = hash >>> 0;
    return (
        ((n & 0xff) << 24)
        | ((n >>> 8 & 0xff) << 16)
        | ((n >>> 16 & 0xff) << 8)
        | (n >>> 24)
    ) >>> 0;
}

// ---- the hash itself --------------------------------------------------------------
//
// Every database type Civ6 writes into a save — units, buildings, districts, techs, civics,
// policies, promotions, terrains, features, resources, improvements, continents, … — is
// identified by CRC-32 of its type name **without the final XOR** (`~crc32(name)`). Tile fields
// store it byte-swapped, instance records straight. Verified against every entry of the sheet
// tables above and against the pairwise-RE unit hashes; `data/civ6-types.json` (generated by
// `npm run types` from the game's own XML) is therefore the complete dictionary.

const CRC_TABLE = (() => {
    const table = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = c & 1 ? (c >>> 1) ^ 0xedb88320 : c >>> 1;
        table[n] = c >>> 0;
    }
    return table;
})();

/** Civ6's hash of a type name: CRC-32 without the final complement. */
export function civ6Hash(name: string): number {
    let crc = 0xffffffff;
    for (const b of Buffer.from(name, 'utf8')) crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ b) & 0xff]!;
    return crc >>> 0;
}

export interface Civ6Type {
    /** `UNIT_WARRIOR` */
    name: string;
    /** `KIND_UNIT` */
    kind: string;
}

const CIV6_TYPES: Record<string, string[]> = civ6TypesJson as Record<string, string[]>;

let typeByHash: Map<number, Civ6Type> | null = null;

function typeIndex(): Map<number, Civ6Type> {
    if (typeByHash) return typeByHash;
    typeByHash = new Map();
    for (const [kind, names] of Object.entries(CIV6_TYPES)) {
        for (const name of names) typeByHash.set(civ6Hash(name), { name, kind });
    }
    return typeByHash;
}

/** The database type behind a hash from either storage form, or null when no type has it. */
export function resolveTypeHash(hash: number): Civ6Type | null {
    if (hash === 0xffffffff || hash === 0) return null;
    const index = typeIndex();
    return index.get(hash >>> 0) ?? index.get(bswap32(hash)) ?? null;
}

/** Same, restricted to one kind (`KIND_UNIT`, `KIND_TECH`, …). */
export function resolveTypeHashOfKind(hash: number, kind: string): string | null {
    const type = resolveTypeHash(hash);
    return type && type.kind === kind ? type.name : null;
}

/** All type names of a kind, for scanning a payload for "any tech hash". */
export function typeNamesOfKind(kind: string): readonly string[] {
    return CIV6_TYPES[kind] ?? [];
}

function lookup<T>(table: Record<string, T>, hash: number): T | null {
    if (hash === 0xffffffff) return null;
    return table[hashHex(hash)] ?? table[hashHex(bswap32(hash))] ?? null;
}

export function resolveTerrain(hash: number): TerrainEntry | null {
    return lookup(TABLES.terrains, hash);
}

export function resolveFeature(hash: number): string | null {
    return lookup(TABLES.features, hash) ?? resolveTypeHashOfKind(hash, 'KIND_FEATURE');
}

export function resolveResource(hash: number): string | null {
    return lookup(TABLES.resources, hash) ?? resolveTypeHashOfKind(hash, 'KIND_RESOURCE');
}

export function resolveImprovement(hash: number): string | null {
    return lookup(TABLES.improvements, hash) ?? resolveTypeHashOfKind(hash, 'KIND_IMPROVEMENT');
}

export function resolveContinent(hash: number): string | null {
    return lookup(TABLES.continents, hash) ?? resolveTypeHashOfKind(hash, 'KIND_CONTINENT');
}

/** Live instance type name (unit/building/district/…): the type dictionary, sheet table as backup. */
export function resolveInstanceType(hash: number): string | null {
    const type = resolveTypeHash(hash);
    if (type) return type.name;
    const table = TABLES.instanceTypes;
    if (!table) return null;
    return table[hashHex(hash)] ?? table[hashHex(bswap32(hash))] ?? null;
}

export function collectUnmappedHashes(tiles: Array<{
    terrainHash: number;
    featureHash: number;
    resourceHash: number;
    improvementHash: number;
    continentHash: number;
}>): {
    terrain: string[];
    features: string[];
    resources: string[];
    improvements: string[];
    continents: string[];
    instanceTypes: string[];
} {
    const terrain = new Set<string>();
    const features = new Set<string>();
    const resources = new Set<string>();
    const improvements = new Set<string>();
    const continents = new Set<string>();
    for (const t of tiles) {
        if (t.terrainHash !== 0xffffffff && !resolveTerrain(t.terrainHash)) {
            terrain.add(hashHex(t.terrainHash));
        }
        if (t.featureHash !== 0xffffffff && !resolveFeature(t.featureHash)) {
            features.add(hashHex(t.featureHash));
        }
        if (t.resourceHash !== 0xffffffff && !resolveResource(t.resourceHash)) {
            resources.add(hashHex(t.resourceHash));
        }
        if (t.improvementHash !== 0xffffffff && !resolveImprovement(t.improvementHash)) {
            improvements.add(hashHex(t.improvementHash));
        }
        if (t.continentHash !== 0xffffffff && !resolveContinent(t.continentHash)) {
            continents.add(hashHex(t.continentHash));
        }
    }
    return {
        terrain: [...terrain].sort(),
        features: [...features].sort(),
        resources: [...resources].sort(),
        improvements: [...improvements].sort(),
        continents: [...continents].sort(),
        instanceTypes: [],
    };
}
